### ISSUE TITLE
Included Country IPs => not tracked

### ISSUE THREAD

**Issue by dev-101** [Findus23/plugin-ExcludeCountries#2]
_(latest Matomo, latest plugin versions)_

Hi, I have set up the plugin to track included countries, and for debugging created a small script to track all unique IPs in a period of time. Since this is a young project, it still receives limited number of visits, so it is easy for me to track everything and debug.

Today 2 IPs from selected country was not tracked at all, but they were in my debug log. They belong to user space (e.g. no bots, cloud services, servers etc.). The only explanation is that maybe they are erroneously reported in MM's database, since recently they have a lot of errors for City field (country, so far, was always correct).

Another reason is that plugin does not work properly in this regard. And, finally, I used my own IPs to test, and - it definitely does not work! I have 0 visits, where it should track my own, since I'm in the 'whitelisted' country field. I used browser that does not block tracker, to make this clear.

Now, I remember it was working initially, with the very first 0.1.0 version (before the language notice fix), and **now I reverted again, and that version is working fine (e.g. it is tracking my own visits)**. 0.1.0-fixed and up do not.

Any ideas what could be wrong?

**Comment by dev-101** [comment]
Could be that added if condition somehow prevents adding country (I have noticed that GDPR find tool does not work for some CC codes, although they do exist in reports):

```
            if (!empty($value["languageCode"])) {
                $codes[] = $value["languageCode"];
            }
```

**Comment by dev-101** [comment]
After cross-checking with server logs, I found that on one IP was most likely a bot hitting specific pages (which do not exist), so the request actually never hit Matomo in the first place, although they are technically matched by location filter. Other one, and mine included, were definitely legit from what I can tell, but they weren't logged. Privacy options are bypassed, so everything is tracked, until I make sure plugin works properly.

**Comment by Findus23** [comment]
Hi,

I don't doubt that when I replaced the hardcoded check with the proper logic from the settings, I mixed something up. I will be taking a closer look in the next few days.

That said, the best way to see if it works as it should is enabling tracker debugging:
https://developer.matomo.org/api-reference/tracking-api#debugging-the-tracker
You should see a line like `request excluded by ExcludeCountries plugin` if the plugin is causing the request to be ignored.

**Comment by dev-101** [comment]
Thank you.

I know, you mentioned it earlier, but Matomo debugging works in browser only for my own requests (I can't see other's browsers and apps), and the file/sql logging seems too convoluted to set up in the first place. This was much faster for me, and this way I will not miss any IP.

**Comment by Findus23** [comment]
And indeed there was a bug: 
https://github.com/Findus23/plugin-ExcludeCountries/commit/fe90e98eb4f0175229fc5dc2a3224eaa70f42573

I had the wrong name in `$codes[] = $value["languageCode"];` after I renamed the setting causing no countries to be selected all the time (and therefore if including is enabled, all requests to be dropped).

This should be fixed in 0.1.3

**Comment by dev-101** [comment]
I have overwritten all files with 0.1.3 and re-defined settings again because of changed variable, but it is still not working. 
e.g. my visits are not being tracked at all (going back to 0.1.0 initial works fine).
Should I uninstall plugin and install it again?

**update:** nope, doesn't help.

**Comment by dev-101** [comment]
~~Btw. I think you should have 3rd case when Exclude is inactive, and no include country is defined. In this case plugin should effectively be inactive (e.g. letting all visits through).~~

we already have this (kind of) with empty excluded mode (default).

**Comment by dev-101** [comment]
@Findus23 

Not sure if you are reading this, but I'll postpone opening the new issue for now.
I have found a source of the bug, and why the logic is not working properly.

```
$provider = LocationProvider::getProviderById(Common::getCurrentLocationProviderId());
$location = $provider->getLocation(["ip" => $request->getIp()]);
$countryCode = strtolower($location[LocationProvider::COUNTRY_CODE_KEY]);
```

**$provider** returns a regular (correct) location object (Piwik\Plugins\GeoIp2\LocationProvider\GeoIp2\Php)

However, the **return value** for **$location** is **boolean false**, which produces an empty string for **$countryCode** later, and that, as a result, produces that **in_array()** checks always runs ("fail"). In another words:

```
if (!in_array($countryCode, $countries)) {
  // always runs
}
```

will always **exclude visit** from a country defined as **to be included**!

Now, I am not sure why **$location** fails tbh.

**Comment by Findus23** [comment]
@dev-101 That makes sense, I didn't consider that the geolocation could fail.
I updated the plugin now that if there is no valid countrycode, it does nothing.
0.1.4 should contain that change.

**Comment by dev-101** [comment]
Well, that's a way to solve it, but why it fails for my IP/CC? That part is not fixed, and it is important. Matomo correctly logs my IP/CC when I disable the plugin.

**Comment by dev-101** [comment]
I think that bug must be in this line here `$location = $provider->getLocation(["ip" => $request->getIp()]);`, maybe the method used to retrieve IP is not correct?

**Comment by Findus23** [comment]
I'll test closer on my live instance.

**Comment by dev-101** [comment]
>don't do anything if no country is detected

Well, tbh, I think this should be optional and left to the admin to decide what to do with such visits.

**Comment by Findus23** [comment]
> I think that bug must be in this line here $location = $provider->getLocation(["ip" => $request->getIp()]);, maybe the method used to retrieve IP is not correct?

You are right, it needs to be `->getIpString()` instead as the geolocation provider converts it back to binary itself.

> Well, tbh, I think this should be optional and left to the admin to decide what to do with such visits.

I could add a setting ([x] exclude requests with unknown location), but I think it should be disabled by default as I'd prefer to drop any requests by default.

**Comment by dev-101** [comment]
Ok, thanks!
edit: Just to confirm that it is working properly now.
